rename table user_without_stats to user_without_stats_old, user_without_stats_temp to user_without_stats;
rename table no_user_for_stats to no_user_for_stats_old, no_user_for_stats_temp to no_user_for_stats;

